name: Update Google Sheets

on:
  push:
    paths:
      - 'sheets/*.csv'  # 'sheets' 폴더 내 CSV 파일에 대한 변경 사항만 감지

jobs:
  update-sheets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 모든 커밋 히스토리를 가져옴

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Identify changed CSV files and update Google Sheets
        env:
          APPS_SCRIPT_URL: "https://script.google.com/macros/s/AKfycbzXNUZLyp3p4S-OMS9-56ZCWd8JI7ycxQM-0rhJbcshm97u-gKGi4nXeE_8iRMW79wy/exec"

        run: python update_sheets.py